version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: test_backend
    container_name: test_backend_c
    ports:
      - "5000:5000"
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: test_frontend
    container_name: test_frontend_c
    command: npm start
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    stdin_open: true
    tty: true    

networks:
    app-network:
        driver: bridge
