version: '3'

services:
  web:
    image: divanshreevatsa/jenkins_test_docker # Assuming this is the Jenkins image you want to use
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: test_backend_c
    ports:
      - "5000:5000"
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: test_frontend_c
    command: npm start
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge
